export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTRATION_SUCCEEDED = 'REGISTRATION_SUCCEEDED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';