// flow-typed signature: 8d12ef4f5595acefbf215f0205216265
// flow-typed version: <<STUB>>/ddp.js_v^2.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ddp.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ddp.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ddp.js/lib/ddp' {
  declare module.exports: any;
}

declare module 'ddp.js/lib/queue' {
  declare module.exports: any;
}

declare module 'ddp.js/lib/socket' {
  declare module.exports: any;
}

declare module 'ddp.js/lib/utils' {
  declare module.exports: any;
}

declare module 'ddp.js/src/ddp' {
  declare module.exports: any;
}

declare module 'ddp.js/src/queue' {
  declare module.exports: any;
}

declare module 'ddp.js/src/socket' {
  declare module.exports: any;
}

declare module 'ddp.js/src/utils' {
  declare module.exports: any;
}

declare module 'ddp.js/test/e2e/connection' {
  declare module.exports: any;
}

declare module 'ddp.js/test/e2e/methods' {
  declare module.exports: any;
}

declare module 'ddp.js/test/e2e/subscriptions' {
  declare module.exports: any;
}

declare module 'ddp.js/test/server/methods' {
  declare module.exports: any;
}

declare module 'ddp.js/test/server/publications' {
  declare module.exports: any;
}

declare module 'ddp.js/test/unit/ddp' {
  declare module.exports: any;
}

declare module 'ddp.js/test/unit/queue' {
  declare module.exports: any;
}

declare module 'ddp.js/test/unit/socket' {
  declare module.exports: any;
}

declare module 'ddp.js/test/unit/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ddp.js/lib/ddp.js' {
  declare module.exports: $Exports<'ddp.js/lib/ddp'>;
}
declare module 'ddp.js/lib/queue.js' {
  declare module.exports: $Exports<'ddp.js/lib/queue'>;
}
declare module 'ddp.js/lib/socket.js' {
  declare module.exports: $Exports<'ddp.js/lib/socket'>;
}
declare module 'ddp.js/lib/utils.js' {
  declare module.exports: $Exports<'ddp.js/lib/utils'>;
}
declare module 'ddp.js/src/ddp.js' {
  declare module.exports: $Exports<'ddp.js/src/ddp'>;
}
declare module 'ddp.js/src/queue.js' {
  declare module.exports: $Exports<'ddp.js/src/queue'>;
}
declare module 'ddp.js/src/socket.js' {
  declare module.exports: $Exports<'ddp.js/src/socket'>;
}
declare module 'ddp.js/src/utils.js' {
  declare module.exports: $Exports<'ddp.js/src/utils'>;
}
declare module 'ddp.js/test/e2e/connection.js' {
  declare module.exports: $Exports<'ddp.js/test/e2e/connection'>;
}
declare module 'ddp.js/test/e2e/methods.js' {
  declare module.exports: $Exports<'ddp.js/test/e2e/methods'>;
}
declare module 'ddp.js/test/e2e/subscriptions.js' {
  declare module.exports: $Exports<'ddp.js/test/e2e/subscriptions'>;
}
declare module 'ddp.js/test/server/methods.js' {
  declare module.exports: $Exports<'ddp.js/test/server/methods'>;
}
declare module 'ddp.js/test/server/publications.js' {
  declare module.exports: $Exports<'ddp.js/test/server/publications'>;
}
declare module 'ddp.js/test/unit/ddp.js' {
  declare module.exports: $Exports<'ddp.js/test/unit/ddp'>;
}
declare module 'ddp.js/test/unit/queue.js' {
  declare module.exports: $Exports<'ddp.js/test/unit/queue'>;
}
declare module 'ddp.js/test/unit/socket.js' {
  declare module.exports: $Exports<'ddp.js/test/unit/socket'>;
}
declare module 'ddp.js/test/unit/utils.js' {
  declare module.exports: $Exports<'ddp.js/test/unit/utils'>;
}
