// flow-typed signature: 30fa1658df35e162ec22a47622e931d2
// flow-typed version: <<STUB>>/most-subject_v^5.3.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'most-subject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'most-subject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'most-subject/lib/commonjs/combinators/complete' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/combinators/error' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/combinators/hold' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/combinators/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/combinators/next' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/interfaces' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/sources/HoldSubjectSource' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/sources/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/subjects/async/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/subjects/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/commonjs/subjects/sync/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/combinators/complete' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/combinators/error' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/combinators/hold' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/combinators/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/combinators/next' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/interfaces' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/sources/HoldSubjectSource' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/sources/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/subjects/async/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/subjects/index' {
  declare module.exports: any;
}

declare module 'most-subject/lib/es2015/subjects/sync/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'most-subject/lib/commonjs/combinators/complete.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/combinators/complete'>;
}
declare module 'most-subject/lib/commonjs/combinators/error.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/combinators/error'>;
}
declare module 'most-subject/lib/commonjs/combinators/hold.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/combinators/hold'>;
}
declare module 'most-subject/lib/commonjs/combinators/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/combinators/index'>;
}
declare module 'most-subject/lib/commonjs/combinators/next.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/combinators/next'>;
}
declare module 'most-subject/lib/commonjs/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/index'>;
}
declare module 'most-subject/lib/commonjs/interfaces.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/interfaces'>;
}
declare module 'most-subject/lib/commonjs/sources/HoldSubjectSource.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/sources/HoldSubjectSource'>;
}
declare module 'most-subject/lib/commonjs/sources/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/sources/index'>;
}
declare module 'most-subject/lib/commonjs/subjects/async/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/subjects/async/index'>;
}
declare module 'most-subject/lib/commonjs/subjects/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/subjects/index'>;
}
declare module 'most-subject/lib/commonjs/subjects/sync/index.js' {
  declare module.exports: $Exports<'most-subject/lib/commonjs/subjects/sync/index'>;
}
declare module 'most-subject/lib/es2015/combinators/complete.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/combinators/complete'>;
}
declare module 'most-subject/lib/es2015/combinators/error.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/combinators/error'>;
}
declare module 'most-subject/lib/es2015/combinators/hold.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/combinators/hold'>;
}
declare module 'most-subject/lib/es2015/combinators/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/combinators/index'>;
}
declare module 'most-subject/lib/es2015/combinators/next.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/combinators/next'>;
}
declare module 'most-subject/lib/es2015/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/index'>;
}
declare module 'most-subject/lib/es2015/interfaces.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/interfaces'>;
}
declare module 'most-subject/lib/es2015/sources/HoldSubjectSource.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/sources/HoldSubjectSource'>;
}
declare module 'most-subject/lib/es2015/sources/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/sources/index'>;
}
declare module 'most-subject/lib/es2015/subjects/async/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/subjects/async/index'>;
}
declare module 'most-subject/lib/es2015/subjects/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/subjects/index'>;
}
declare module 'most-subject/lib/es2015/subjects/sync/index.js' {
  declare module.exports: $Exports<'most-subject/lib/es2015/subjects/sync/index'>;
}
