// flow-typed signature: 1eab76b3be7c0539517ce1c03a47b38e
// flow-typed version: <<STUB>>/most_v^1.1.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'most'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'most' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'most/dist/most' {
  declare module.exports: any;
}

declare module 'most/dist/most.min' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/accumulate' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/applicative' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/build' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/combine' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/concatMap' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/continueWith' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/delay' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/errors' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/filter' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/flatMap' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/limit' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/loop' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/merge' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/mergeConcurrently' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/observe' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/promises' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/sample' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/slice' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/switch' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/thru' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/timeslice' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/timestamp' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/transduce' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/transform' {
  declare module.exports: any;
}

declare module 'most/lib/combinator/zip' {
  declare module.exports: any;
}

declare module 'most/lib/disposable/Disposable' {
  declare module.exports: any;
}

declare module 'most/lib/disposable/dispose' {
  declare module.exports: any;
}

declare module 'most/lib/disposable/SettableDisposable' {
  declare module.exports: any;
}

declare module 'most/lib/fatalError' {
  declare module.exports: any;
}

declare module 'most/lib/fusion/Filter' {
  declare module.exports: any;
}

declare module 'most/lib/fusion/FilterMap' {
  declare module.exports: any;
}

declare module 'most/lib/fusion/Map' {
  declare module.exports: any;
}

declare module 'most/lib/index' {
  declare module.exports: any;
}

declare module 'most/lib/invoke' {
  declare module.exports: any;
}

declare module 'most/lib/iterable' {
  declare module.exports: any;
}

declare module 'most/lib/LinkedList' {
  declare module.exports: any;
}

declare module 'most/lib/observable/fromObservable' {
  declare module.exports: any;
}

declare module 'most/lib/observable/getObservable' {
  declare module.exports: any;
}

declare module 'most/lib/observable/subscribe' {
  declare module.exports: any;
}

declare module 'most/lib/Promise' {
  declare module.exports: any;
}

declare module 'most/lib/Queue' {
  declare module.exports: any;
}

declare module 'most/lib/runSource' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/ClockTimer' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/defaultScheduler' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/PropagateTask' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/ScheduledTask' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/Scheduler' {
  declare module.exports: any;
}

declare module 'most/lib/scheduler/Timeline' {
  declare module.exports: any;
}

declare module 'most/lib/sink/DeferredSink' {
  declare module.exports: any;
}

declare module 'most/lib/sink/IndexSink' {
  declare module.exports: any;
}

declare module 'most/lib/sink/Pipe' {
  declare module.exports: any;
}

declare module 'most/lib/sink/SafeSink' {
  declare module.exports: any;
}

declare module 'most/lib/source/core' {
  declare module.exports: any;
}

declare module 'most/lib/source/EventEmitterSource' {
  declare module.exports: any;
}

declare module 'most/lib/source/EventTargetSource' {
  declare module.exports: any;
}

declare module 'most/lib/source/from' {
  declare module.exports: any;
}

declare module 'most/lib/source/fromArray' {
  declare module.exports: any;
}

declare module 'most/lib/source/fromEvent' {
  declare module.exports: any;
}

declare module 'most/lib/source/fromIterable' {
  declare module.exports: any;
}

declare module 'most/lib/source/generate' {
  declare module.exports: any;
}

declare module 'most/lib/source/iterate' {
  declare module.exports: any;
}

declare module 'most/lib/source/periodic' {
  declare module.exports: any;
}

declare module 'most/lib/source/tryEvent' {
  declare module.exports: any;
}

declare module 'most/lib/source/unfold' {
  declare module.exports: any;
}

declare module 'most/lib/Stream' {
  declare module.exports: any;
}

declare module 'most/lib/task' {
  declare module.exports: any;
}

declare module 'most/src/combinator/accumulate' {
  declare module.exports: any;
}

declare module 'most/src/combinator/applicative' {
  declare module.exports: any;
}

declare module 'most/src/combinator/build' {
  declare module.exports: any;
}

declare module 'most/src/combinator/combine' {
  declare module.exports: any;
}

declare module 'most/src/combinator/concatMap' {
  declare module.exports: any;
}

declare module 'most/src/combinator/continueWith' {
  declare module.exports: any;
}

declare module 'most/src/combinator/delay' {
  declare module.exports: any;
}

declare module 'most/src/combinator/errors' {
  declare module.exports: any;
}

declare module 'most/src/combinator/filter' {
  declare module.exports: any;
}

declare module 'most/src/combinator/flatMap' {
  declare module.exports: any;
}

declare module 'most/src/combinator/limit' {
  declare module.exports: any;
}

declare module 'most/src/combinator/loop' {
  declare module.exports: any;
}

declare module 'most/src/combinator/merge' {
  declare module.exports: any;
}

declare module 'most/src/combinator/mergeConcurrently' {
  declare module.exports: any;
}

declare module 'most/src/combinator/observe' {
  declare module.exports: any;
}

declare module 'most/src/combinator/promises' {
  declare module.exports: any;
}

declare module 'most/src/combinator/sample' {
  declare module.exports: any;
}

declare module 'most/src/combinator/slice' {
  declare module.exports: any;
}

declare module 'most/src/combinator/switch' {
  declare module.exports: any;
}

declare module 'most/src/combinator/thru' {
  declare module.exports: any;
}

declare module 'most/src/combinator/timeslice' {
  declare module.exports: any;
}

declare module 'most/src/combinator/timestamp' {
  declare module.exports: any;
}

declare module 'most/src/combinator/transduce' {
  declare module.exports: any;
}

declare module 'most/src/combinator/transform' {
  declare module.exports: any;
}

declare module 'most/src/combinator/zip' {
  declare module.exports: any;
}

declare module 'most/src/disposable/Disposable' {
  declare module.exports: any;
}

declare module 'most/src/disposable/dispose' {
  declare module.exports: any;
}

declare module 'most/src/disposable/SettableDisposable' {
  declare module.exports: any;
}

declare module 'most/src/fatalError' {
  declare module.exports: any;
}

declare module 'most/src/fusion/Filter' {
  declare module.exports: any;
}

declare module 'most/src/fusion/FilterMap' {
  declare module.exports: any;
}

declare module 'most/src/fusion/Map' {
  declare module.exports: any;
}

declare module 'most/src/index' {
  declare module.exports: any;
}

declare module 'most/src/invoke' {
  declare module.exports: any;
}

declare module 'most/src/iterable' {
  declare module.exports: any;
}

declare module 'most/src/LinkedList' {
  declare module.exports: any;
}

declare module 'most/src/observable/fromObservable' {
  declare module.exports: any;
}

declare module 'most/src/observable/getObservable' {
  declare module.exports: any;
}

declare module 'most/src/observable/subscribe' {
  declare module.exports: any;
}

declare module 'most/src/Promise' {
  declare module.exports: any;
}

declare module 'most/src/Queue' {
  declare module.exports: any;
}

declare module 'most/src/runSource' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/ClockTimer' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/defaultScheduler' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/PropagateTask' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/ScheduledTask' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/Scheduler' {
  declare module.exports: any;
}

declare module 'most/src/scheduler/Timeline' {
  declare module.exports: any;
}

declare module 'most/src/sink/DeferredSink' {
  declare module.exports: any;
}

declare module 'most/src/sink/IndexSink' {
  declare module.exports: any;
}

declare module 'most/src/sink/Pipe' {
  declare module.exports: any;
}

declare module 'most/src/sink/SafeSink' {
  declare module.exports: any;
}

declare module 'most/src/source/core' {
  declare module.exports: any;
}

declare module 'most/src/source/EventEmitterSource' {
  declare module.exports: any;
}

declare module 'most/src/source/EventTargetSource' {
  declare module.exports: any;
}

declare module 'most/src/source/from' {
  declare module.exports: any;
}

declare module 'most/src/source/fromArray' {
  declare module.exports: any;
}

declare module 'most/src/source/fromEvent' {
  declare module.exports: any;
}

declare module 'most/src/source/fromIterable' {
  declare module.exports: any;
}

declare module 'most/src/source/generate' {
  declare module.exports: any;
}

declare module 'most/src/source/iterate' {
  declare module.exports: any;
}

declare module 'most/src/source/periodic' {
  declare module.exports: any;
}

declare module 'most/src/source/tryEvent' {
  declare module.exports: any;
}

declare module 'most/src/source/unfold' {
  declare module.exports: any;
}

declare module 'most/src/Stream' {
  declare module.exports: any;
}

declare module 'most/src/task' {
  declare module.exports: any;
}

// Filename aliases
declare module 'most/dist/most.js' {
  declare module.exports: $Exports<'most/dist/most'>;
}
declare module 'most/dist/most.min.js' {
  declare module.exports: $Exports<'most/dist/most.min'>;
}
declare module 'most/lib/combinator/accumulate.js' {
  declare module.exports: $Exports<'most/lib/combinator/accumulate'>;
}
declare module 'most/lib/combinator/applicative.js' {
  declare module.exports: $Exports<'most/lib/combinator/applicative'>;
}
declare module 'most/lib/combinator/build.js' {
  declare module.exports: $Exports<'most/lib/combinator/build'>;
}
declare module 'most/lib/combinator/combine.js' {
  declare module.exports: $Exports<'most/lib/combinator/combine'>;
}
declare module 'most/lib/combinator/concatMap.js' {
  declare module.exports: $Exports<'most/lib/combinator/concatMap'>;
}
declare module 'most/lib/combinator/continueWith.js' {
  declare module.exports: $Exports<'most/lib/combinator/continueWith'>;
}
declare module 'most/lib/combinator/delay.js' {
  declare module.exports: $Exports<'most/lib/combinator/delay'>;
}
declare module 'most/lib/combinator/errors.js' {
  declare module.exports: $Exports<'most/lib/combinator/errors'>;
}
declare module 'most/lib/combinator/filter.js' {
  declare module.exports: $Exports<'most/lib/combinator/filter'>;
}
declare module 'most/lib/combinator/flatMap.js' {
  declare module.exports: $Exports<'most/lib/combinator/flatMap'>;
}
declare module 'most/lib/combinator/limit.js' {
  declare module.exports: $Exports<'most/lib/combinator/limit'>;
}
declare module 'most/lib/combinator/loop.js' {
  declare module.exports: $Exports<'most/lib/combinator/loop'>;
}
declare module 'most/lib/combinator/merge.js' {
  declare module.exports: $Exports<'most/lib/combinator/merge'>;
}
declare module 'most/lib/combinator/mergeConcurrently.js' {
  declare module.exports: $Exports<'most/lib/combinator/mergeConcurrently'>;
}
declare module 'most/lib/combinator/observe.js' {
  declare module.exports: $Exports<'most/lib/combinator/observe'>;
}
declare module 'most/lib/combinator/promises.js' {
  declare module.exports: $Exports<'most/lib/combinator/promises'>;
}
declare module 'most/lib/combinator/sample.js' {
  declare module.exports: $Exports<'most/lib/combinator/sample'>;
}
declare module 'most/lib/combinator/slice.js' {
  declare module.exports: $Exports<'most/lib/combinator/slice'>;
}
declare module 'most/lib/combinator/switch.js' {
  declare module.exports: $Exports<'most/lib/combinator/switch'>;
}
declare module 'most/lib/combinator/thru.js' {
  declare module.exports: $Exports<'most/lib/combinator/thru'>;
}
declare module 'most/lib/combinator/timeslice.js' {
  declare module.exports: $Exports<'most/lib/combinator/timeslice'>;
}
declare module 'most/lib/combinator/timestamp.js' {
  declare module.exports: $Exports<'most/lib/combinator/timestamp'>;
}
declare module 'most/lib/combinator/transduce.js' {
  declare module.exports: $Exports<'most/lib/combinator/transduce'>;
}
declare module 'most/lib/combinator/transform.js' {
  declare module.exports: $Exports<'most/lib/combinator/transform'>;
}
declare module 'most/lib/combinator/zip.js' {
  declare module.exports: $Exports<'most/lib/combinator/zip'>;
}
declare module 'most/lib/disposable/Disposable.js' {
  declare module.exports: $Exports<'most/lib/disposable/Disposable'>;
}
declare module 'most/lib/disposable/dispose.js' {
  declare module.exports: $Exports<'most/lib/disposable/dispose'>;
}
declare module 'most/lib/disposable/SettableDisposable.js' {
  declare module.exports: $Exports<'most/lib/disposable/SettableDisposable'>;
}
declare module 'most/lib/fatalError.js' {
  declare module.exports: $Exports<'most/lib/fatalError'>;
}
declare module 'most/lib/fusion/Filter.js' {
  declare module.exports: $Exports<'most/lib/fusion/Filter'>;
}
declare module 'most/lib/fusion/FilterMap.js' {
  declare module.exports: $Exports<'most/lib/fusion/FilterMap'>;
}
declare module 'most/lib/fusion/Map.js' {
  declare module.exports: $Exports<'most/lib/fusion/Map'>;
}
declare module 'most/lib/index.js' {
  declare module.exports: $Exports<'most/lib/index'>;
}
declare module 'most/lib/invoke.js' {
  declare module.exports: $Exports<'most/lib/invoke'>;
}
declare module 'most/lib/iterable.js' {
  declare module.exports: $Exports<'most/lib/iterable'>;
}
declare module 'most/lib/LinkedList.js' {
  declare module.exports: $Exports<'most/lib/LinkedList'>;
}
declare module 'most/lib/observable/fromObservable.js' {
  declare module.exports: $Exports<'most/lib/observable/fromObservable'>;
}
declare module 'most/lib/observable/getObservable.js' {
  declare module.exports: $Exports<'most/lib/observable/getObservable'>;
}
declare module 'most/lib/observable/subscribe.js' {
  declare module.exports: $Exports<'most/lib/observable/subscribe'>;
}
declare module 'most/lib/Promise.js' {
  declare module.exports: $Exports<'most/lib/Promise'>;
}
declare module 'most/lib/Queue.js' {
  declare module.exports: $Exports<'most/lib/Queue'>;
}
declare module 'most/lib/runSource.js' {
  declare module.exports: $Exports<'most/lib/runSource'>;
}
declare module 'most/lib/scheduler/ClockTimer.js' {
  declare module.exports: $Exports<'most/lib/scheduler/ClockTimer'>;
}
declare module 'most/lib/scheduler/defaultScheduler.js' {
  declare module.exports: $Exports<'most/lib/scheduler/defaultScheduler'>;
}
declare module 'most/lib/scheduler/PropagateTask.js' {
  declare module.exports: $Exports<'most/lib/scheduler/PropagateTask'>;
}
declare module 'most/lib/scheduler/ScheduledTask.js' {
  declare module.exports: $Exports<'most/lib/scheduler/ScheduledTask'>;
}
declare module 'most/lib/scheduler/Scheduler.js' {
  declare module.exports: $Exports<'most/lib/scheduler/Scheduler'>;
}
declare module 'most/lib/scheduler/Timeline.js' {
  declare module.exports: $Exports<'most/lib/scheduler/Timeline'>;
}
declare module 'most/lib/sink/DeferredSink.js' {
  declare module.exports: $Exports<'most/lib/sink/DeferredSink'>;
}
declare module 'most/lib/sink/IndexSink.js' {
  declare module.exports: $Exports<'most/lib/sink/IndexSink'>;
}
declare module 'most/lib/sink/Pipe.js' {
  declare module.exports: $Exports<'most/lib/sink/Pipe'>;
}
declare module 'most/lib/sink/SafeSink.js' {
  declare module.exports: $Exports<'most/lib/sink/SafeSink'>;
}
declare module 'most/lib/source/core.js' {
  declare module.exports: $Exports<'most/lib/source/core'>;
}
declare module 'most/lib/source/EventEmitterSource.js' {
  declare module.exports: $Exports<'most/lib/source/EventEmitterSource'>;
}
declare module 'most/lib/source/EventTargetSource.js' {
  declare module.exports: $Exports<'most/lib/source/EventTargetSource'>;
}
declare module 'most/lib/source/from.js' {
  declare module.exports: $Exports<'most/lib/source/from'>;
}
declare module 'most/lib/source/fromArray.js' {
  declare module.exports: $Exports<'most/lib/source/fromArray'>;
}
declare module 'most/lib/source/fromEvent.js' {
  declare module.exports: $Exports<'most/lib/source/fromEvent'>;
}
declare module 'most/lib/source/fromIterable.js' {
  declare module.exports: $Exports<'most/lib/source/fromIterable'>;
}
declare module 'most/lib/source/generate.js' {
  declare module.exports: $Exports<'most/lib/source/generate'>;
}
declare module 'most/lib/source/iterate.js' {
  declare module.exports: $Exports<'most/lib/source/iterate'>;
}
declare module 'most/lib/source/periodic.js' {
  declare module.exports: $Exports<'most/lib/source/periodic'>;
}
declare module 'most/lib/source/tryEvent.js' {
  declare module.exports: $Exports<'most/lib/source/tryEvent'>;
}
declare module 'most/lib/source/unfold.js' {
  declare module.exports: $Exports<'most/lib/source/unfold'>;
}
declare module 'most/lib/Stream.js' {
  declare module.exports: $Exports<'most/lib/Stream'>;
}
declare module 'most/lib/task.js' {
  declare module.exports: $Exports<'most/lib/task'>;
}
declare module 'most/src/combinator/accumulate.js' {
  declare module.exports: $Exports<'most/src/combinator/accumulate'>;
}
declare module 'most/src/combinator/applicative.js' {
  declare module.exports: $Exports<'most/src/combinator/applicative'>;
}
declare module 'most/src/combinator/build.js' {
  declare module.exports: $Exports<'most/src/combinator/build'>;
}
declare module 'most/src/combinator/combine.js' {
  declare module.exports: $Exports<'most/src/combinator/combine'>;
}
declare module 'most/src/combinator/concatMap.js' {
  declare module.exports: $Exports<'most/src/combinator/concatMap'>;
}
declare module 'most/src/combinator/continueWith.js' {
  declare module.exports: $Exports<'most/src/combinator/continueWith'>;
}
declare module 'most/src/combinator/delay.js' {
  declare module.exports: $Exports<'most/src/combinator/delay'>;
}
declare module 'most/src/combinator/errors.js' {
  declare module.exports: $Exports<'most/src/combinator/errors'>;
}
declare module 'most/src/combinator/filter.js' {
  declare module.exports: $Exports<'most/src/combinator/filter'>;
}
declare module 'most/src/combinator/flatMap.js' {
  declare module.exports: $Exports<'most/src/combinator/flatMap'>;
}
declare module 'most/src/combinator/limit.js' {
  declare module.exports: $Exports<'most/src/combinator/limit'>;
}
declare module 'most/src/combinator/loop.js' {
  declare module.exports: $Exports<'most/src/combinator/loop'>;
}
declare module 'most/src/combinator/merge.js' {
  declare module.exports: $Exports<'most/src/combinator/merge'>;
}
declare module 'most/src/combinator/mergeConcurrently.js' {
  declare module.exports: $Exports<'most/src/combinator/mergeConcurrently'>;
}
declare module 'most/src/combinator/observe.js' {
  declare module.exports: $Exports<'most/src/combinator/observe'>;
}
declare module 'most/src/combinator/promises.js' {
  declare module.exports: $Exports<'most/src/combinator/promises'>;
}
declare module 'most/src/combinator/sample.js' {
  declare module.exports: $Exports<'most/src/combinator/sample'>;
}
declare module 'most/src/combinator/slice.js' {
  declare module.exports: $Exports<'most/src/combinator/slice'>;
}
declare module 'most/src/combinator/switch.js' {
  declare module.exports: $Exports<'most/src/combinator/switch'>;
}
declare module 'most/src/combinator/thru.js' {
  declare module.exports: $Exports<'most/src/combinator/thru'>;
}
declare module 'most/src/combinator/timeslice.js' {
  declare module.exports: $Exports<'most/src/combinator/timeslice'>;
}
declare module 'most/src/combinator/timestamp.js' {
  declare module.exports: $Exports<'most/src/combinator/timestamp'>;
}
declare module 'most/src/combinator/transduce.js' {
  declare module.exports: $Exports<'most/src/combinator/transduce'>;
}
declare module 'most/src/combinator/transform.js' {
  declare module.exports: $Exports<'most/src/combinator/transform'>;
}
declare module 'most/src/combinator/zip.js' {
  declare module.exports: $Exports<'most/src/combinator/zip'>;
}
declare module 'most/src/disposable/Disposable.js' {
  declare module.exports: $Exports<'most/src/disposable/Disposable'>;
}
declare module 'most/src/disposable/dispose.js' {
  declare module.exports: $Exports<'most/src/disposable/dispose'>;
}
declare module 'most/src/disposable/SettableDisposable.js' {
  declare module.exports: $Exports<'most/src/disposable/SettableDisposable'>;
}
declare module 'most/src/fatalError.js' {
  declare module.exports: $Exports<'most/src/fatalError'>;
}
declare module 'most/src/fusion/Filter.js' {
  declare module.exports: $Exports<'most/src/fusion/Filter'>;
}
declare module 'most/src/fusion/FilterMap.js' {
  declare module.exports: $Exports<'most/src/fusion/FilterMap'>;
}
declare module 'most/src/fusion/Map.js' {
  declare module.exports: $Exports<'most/src/fusion/Map'>;
}
declare module 'most/src/index.js' {
  declare module.exports: $Exports<'most/src/index'>;
}
declare module 'most/src/invoke.js' {
  declare module.exports: $Exports<'most/src/invoke'>;
}
declare module 'most/src/iterable.js' {
  declare module.exports: $Exports<'most/src/iterable'>;
}
declare module 'most/src/LinkedList.js' {
  declare module.exports: $Exports<'most/src/LinkedList'>;
}
declare module 'most/src/observable/fromObservable.js' {
  declare module.exports: $Exports<'most/src/observable/fromObservable'>;
}
declare module 'most/src/observable/getObservable.js' {
  declare module.exports: $Exports<'most/src/observable/getObservable'>;
}
declare module 'most/src/observable/subscribe.js' {
  declare module.exports: $Exports<'most/src/observable/subscribe'>;
}
declare module 'most/src/Promise.js' {
  declare module.exports: $Exports<'most/src/Promise'>;
}
declare module 'most/src/Queue.js' {
  declare module.exports: $Exports<'most/src/Queue'>;
}
declare module 'most/src/runSource.js' {
  declare module.exports: $Exports<'most/src/runSource'>;
}
declare module 'most/src/scheduler/ClockTimer.js' {
  declare module.exports: $Exports<'most/src/scheduler/ClockTimer'>;
}
declare module 'most/src/scheduler/defaultScheduler.js' {
  declare module.exports: $Exports<'most/src/scheduler/defaultScheduler'>;
}
declare module 'most/src/scheduler/PropagateTask.js' {
  declare module.exports: $Exports<'most/src/scheduler/PropagateTask'>;
}
declare module 'most/src/scheduler/ScheduledTask.js' {
  declare module.exports: $Exports<'most/src/scheduler/ScheduledTask'>;
}
declare module 'most/src/scheduler/Scheduler.js' {
  declare module.exports: $Exports<'most/src/scheduler/Scheduler'>;
}
declare module 'most/src/scheduler/Timeline.js' {
  declare module.exports: $Exports<'most/src/scheduler/Timeline'>;
}
declare module 'most/src/sink/DeferredSink.js' {
  declare module.exports: $Exports<'most/src/sink/DeferredSink'>;
}
declare module 'most/src/sink/IndexSink.js' {
  declare module.exports: $Exports<'most/src/sink/IndexSink'>;
}
declare module 'most/src/sink/Pipe.js' {
  declare module.exports: $Exports<'most/src/sink/Pipe'>;
}
declare module 'most/src/sink/SafeSink.js' {
  declare module.exports: $Exports<'most/src/sink/SafeSink'>;
}
declare module 'most/src/source/core.js' {
  declare module.exports: $Exports<'most/src/source/core'>;
}
declare module 'most/src/source/EventEmitterSource.js' {
  declare module.exports: $Exports<'most/src/source/EventEmitterSource'>;
}
declare module 'most/src/source/EventTargetSource.js' {
  declare module.exports: $Exports<'most/src/source/EventTargetSource'>;
}
declare module 'most/src/source/from.js' {
  declare module.exports: $Exports<'most/src/source/from'>;
}
declare module 'most/src/source/fromArray.js' {
  declare module.exports: $Exports<'most/src/source/fromArray'>;
}
declare module 'most/src/source/fromEvent.js' {
  declare module.exports: $Exports<'most/src/source/fromEvent'>;
}
declare module 'most/src/source/fromIterable.js' {
  declare module.exports: $Exports<'most/src/source/fromIterable'>;
}
declare module 'most/src/source/generate.js' {
  declare module.exports: $Exports<'most/src/source/generate'>;
}
declare module 'most/src/source/iterate.js' {
  declare module.exports: $Exports<'most/src/source/iterate'>;
}
declare module 'most/src/source/periodic.js' {
  declare module.exports: $Exports<'most/src/source/periodic'>;
}
declare module 'most/src/source/tryEvent.js' {
  declare module.exports: $Exports<'most/src/source/tryEvent'>;
}
declare module 'most/src/source/unfold.js' {
  declare module.exports: $Exports<'most/src/source/unfold'>;
}
declare module 'most/src/Stream.js' {
  declare module.exports: $Exports<'most/src/Stream'>;
}
declare module 'most/src/task.js' {
  declare module.exports: $Exports<'most/src/task'>;
}
