// flow-typed signature: 29543d0f163a71de378545ff15e29ef8
// flow-typed version: <<STUB>>/react-native-mauron85-background-geolocation_v^0.2.0-alpha.5/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mauron85-background-geolocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mauron85-background-geolocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-mauron85-background-geolocation/index' {
  declare module.exports: $Exports<'react-native-mauron85-background-geolocation'>;
}
declare module 'react-native-mauron85-background-geolocation/index.js' {
  declare module.exports: $Exports<'react-native-mauron85-background-geolocation'>;
}
