// flow-typed signature: 6c43edd70a3115f579f70a523f7bbdad
// flow-typed version: <<STUB>>/redux-observable-adapter-most_v0.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-observable-adapter-most'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-observable-adapter-most' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-observable-adapter-most/dist/redux-observable-adapter-most' {
  declare module.exports: any;
}

declare module 'redux-observable-adapter-most/dist/redux-observable-adapter-most.min' {
  declare module.exports: any;
}

declare module 'redux-observable-adapter-most/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-observable-adapter-most/dist/redux-observable-adapter-most.js' {
  declare module.exports: $Exports<'redux-observable-adapter-most/dist/redux-observable-adapter-most'>;
}
declare module 'redux-observable-adapter-most/dist/redux-observable-adapter-most.min.js' {
  declare module.exports: $Exports<'redux-observable-adapter-most/dist/redux-observable-adapter-most.min'>;
}
declare module 'redux-observable-adapter-most/lib/index.js' {
  declare module.exports: $Exports<'redux-observable-adapter-most/lib/index'>;
}
