export const NOTIFICATIONS_SUB_READY = 'NOTIFICATIONS_SUB_READY';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const NOTIFICATION_UPDATED = 'NOTIFICATION_UPDATED';
export const MARK_NOTIFICATION_AS_READ_REQUESTED = 'MARK_NOTIFICATION_AS_READ_REQUESTED';