export const USER_LOCATION_RECEIVED = 'USER_LOCATION_RECEIVED';
export const START_BACKGROUND_TRACKING = 'START_BACKGROUND_TRACKING';
export const STOP_BACKGROUND_TRACKING = 'STOP_BACKGROUND_TRACKING';
export const USERS_LOCATION_SUBSCRIPTION_REQUESTED = 'USERS_LOCATION_SUBSCRIPTION_REQUESTED';