export const USER_REQUESTED_RIDE = 'USER_REQUESTED_RIDE';
export const USER_RECEIVED_RIDE_REQUEST = 'USER_RECEIVED_RIDE_REQUEST';
export const USER_ACCEPTED_RIDE_REQUEST = 'USER_ACCEPTED_RIDE_REQUEST';
export const USERS_RIDE_REQUEST_GOT_ACCEPTED = 'USERS_RIDE_REQUEST_GOT_ACCEPTED';
export const TRIP_COMPLETED = ' TRIP_COMPLETED';
