export const USER_REQUESTED_RIDE = 'USER_REQUESTED_RIDE';
export const USER_RECEIVED_RIDE_REQUEST = 'USER_RECEIVED_RIDE_REQUEST';
export const USER_ACCEPTED_RIDE_REQUEST = 'USER_ACCEPTED_RIDE_REQUEST';
export const USERS_RIDE_REQUEST_GOT_ACCEPTED = 'USERS_RIDE_REQUEST_GOT_ACCEPTED';
export const USER_WITHDRAWN_RIDE_REQUEST = 'USER_WITHDRAWN_RIDE_REQUEST';
export const TRIP_COMPLETED = ' TRIP_COMPLETED';

export const USER_DATA_UPDATED = 'USER_DATA_UPDATED';
export const DRIVER_DATA_UPDATED = 'DRIVER_DATA_UPDATED';
export const RIDER_DATA_UPDATED = 'RIDER_DATA_UPDATED';
export const REQUESTER_DATA_UPDATED = 'REQUESTER_DATA_UPDATED';
export const USERS_ROLE_UPDATED = 'USERS_ROLE_UPDATED';

export const FAST_TRACKING_STARTED = 'FAST_TRACKING_STARTED';
export const FAST_TRACKING_STOPPED = 'FAST_TRACKING_STOPPED';